@echo off
echo Iniciando el servidor de la Bodega...
start /b node index.js
echo Esperando a que el servidor este listo...
timeout /t 3 /nobreak > nul
echo Abriendo la aplicacion en el navegador...
start http://localhost:3000
exit
